#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

set -e

err() {
    exitval=$1
    shift
    echo "$*" 1>&2
    exit $exitval
}

_MYDIR=$(dirname `realpath $0`)
[ ! -f "${_MYDIR}/../cpr.inc" ] && err 1 "Missed cpr.inc in ${_MYDIR}"
. ${_MYDIR}/../cpr.inc

# MAIN()
while getopts "v:a:t:s:" opt; do
        case "${opt}" in
            v) ver="${OPTARG}" ;;
            a) oarch="${OPTARG}" ;;
            t) targetarch="${OPTARG}" ;;
	    s) STABLE="${OPTARG}" ;;
            *) usage ;;
        esac
    shift $(($OPTIND - 1))
done

[ -z "${ver}" ] && err 1 "Give me version, e.g: -v 11.0"
[ -z "${stable}" ] && STABLE=0

. ${_MYDIR}/../build.inc

_MASTERLINK="${ver}"
_SLAVELINK="${_MASTERLINK}-slave"

. ${_MYDIR}/../postarg.inc

set +e
    [ ! -d "${_MYDOCROOT}" ] && mkdir -p ${_MYDOCROOT}
set -e

DST_DIR="${_MYDOCROOT}/${_SLAVELINK}"

set +e
    [ ! -h "${DST_DIR}" ] && ${_MYDIR}/swroot_base -v "${ver}" -a "${arch}" -t "${targetarch}"
set -e

cbsd mkdistribution ver=${ver} arch="${arch}" targetarch="${targetarch}" dstdir=${DST_DIR}
