#!/bin/sh

set -e

err() {
    exitval=$1
    shift
    echo "$*" 1>&2
    exit $exitval
}

_MYDIR=$(dirname `realpath $0`)
[ ! -f "${_MYDIR}/../cpr.inc" ] && err 1 "Missed cpr.inc in ${_MYDIR}"
. ${_MYDIR}/../cpr.inc

# MAIN()
while getopts "v:a:t:n:" opt; do
	case "${opt}" in
	    v) _VER="${OPTARG}" ;;
	    a) _ARCH="${OPTARG}" ;;
	    t) _TARGET_ARCH="${OPTARG}" ;;
	    n) _NAME="${OPTARG}" ;;
	    *)  usage ;;
	esac
    shift $(($OPTIND - 1))
done

[ -z "${_VER}" ] && err 1 "Give me version, e.g: -v 10.0"
[ -z "${_NAME}" ] && err 1 "Give me name, e.g: -n redmine"

. ${_MYDIR}/../postarg.inc

FOLDERS="${_NAME} ${_NAME}-1 ${_NAME}-2 ${_NAME}-slave"

set +e
    [ ! -d "${_IMGMYDOCROOT}" ] && mkdir -p ${_IMGMYDOCROOT}
set -e

for i in ${_HST}; do
	echo $i
	DST_DIR="${_REMOTEDOCROOT}/img/${FHIER}/${_VER}"
	ssh ${i} -C "mkdir -p ${DST_DIR} 2>/dev/null"
	for n in ${FOLDERS}; do
	#    /usr/local/bin/rsync -avz4 -lHt --delete-after --password-file=/root/etc/cbsd.secrets ${_DOCROOTBASE}/${n} rsync://cbsd@${i}/dl.bsdstore.ru/img/${FHIER}
#	    set -x xtrace
	    rsync -avz4 -e ssh -lHt ${_IMGMYDOCROOT}/${n} root@${i}:${DST_DIR}
#	    set +x xtrace
	done
done
